### ISSUE TITLE
Issue with calling a function on confirmation callback

### ISSUE THREAD

**Issue by HariPrasad-1493** [abhishek-misra/confirm-dialog#1]
Hi , 
I'm also facing the same issue where calling another function on confirmation callback 
when called - 
this.confirmDialogService.confirmThis("Are you sure to delete?", function () {        
     this.dosomething();    
  },
   function () {  
      alert("No clicked");  
    })
ERR:
Cannot read property 'dosomething' of undefined

**Comment by HariPrasad-1493** [comment]
for some reason, the same solution in service needs to be applied to call a local function - 
**const that = this; ==> add new instance**
this.confirmDialogService.confirmThis("Are you sure to delete?", function () {
**that**.dosomething(); **==> call with that instance**
},
function () {
alert("No clicked");
})

**Comment by abhishek-misra** [comment]
I @HariPrasad-1493  Thanks for feedback Will Fix this issue in next release
